package day20.model;

public enum Position {
    ORIGINAL,
    FLIPPED_VERTICAL,
    FLIPPED_HORIZONTAL,
    FLIPPED_DIAGONAL_TOP_LEFT,
    FLIPPED_DIAGONAL_TOP_RIGHT,
    ROTATE_90_CLOCK,
    ROTATE_180_CLOCK,
    ROTATE_270_CLOCK
}
